### ISSUE TITLE
There is no function named net.load_state_dict in code.

### ISSUE THREAD

**Issue by avnishbhagwate** [theSage21/lorentz-embeddings#13]
I am trying to run custom dataset with with 3993 rows(columns) with entries>=1. The code calls for the function _**net.load_state_dict**_ but there is no definition whatsoever in the code.

**Comment by theSage21** [comment]
umm, I'm not sure what you are asking. Is there an error you are facing? The function you are talking about is there by default in Pytorch.

https://pytorch.org/docs/stable/nn.html#torch.nn.Module.load_state_dict

**Comment by avnishbhagwate** [comment]
Is it necessary that the graph that is to be embedded has to be a connected graph and/or a directed one? I have a disconnected graph and I am getting error "Node {i} has no parent and no child".

**Comment by theSage21** [comment]
duplicate content in #14
